version: '3.5'

services:
  # Backend Service for User Side
  userside:
    build:
      context: .
    container_name: maya-userside
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
          ignore: 
            - /node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "5001:5001" # Expose port 5001 for the backend
    env_file:
      - .env # Use the existing .env file for environment variables
    volumes:
      - .:/app # Mount the current directory into the container for live changes
      - /app/node_modules # Ignore node_modules to prevent conflicts
    command: ["npx", "nodemon", "userside/src/index.js"]
    networks:
      - milvus_network # Connect to the external Milvus network
      - kafka_network # Connect to the external Kafka network
networks:
  milvus_network:
    external: true
  kafka_network:
    external: true
